### ISSUE TITLE
[Improvement]: questions on software packages

### ISSUE THREAD

**Issue by yf13** [kendryte/k230_docs#11]
### Improvement

Hi,

I am having a few questions regarding various software packages but no answers can be found from current (v0.9) documents:

- What do `CDK` and `MPP` mean? I am guessing MPP is for `Media Processing Package` and `CDK` is related to inter-CPU coordinations but I am not sure. 
- Where do `CDK` and `MPP` sit in [this software stack figure 1.1](https://gitee.com/kendryte/k230_docs/blob/main/zh/01_software/board/K230_SDK_%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md)?
- What is the use of `src/little/buildroot-ext/buildroot-9d1d4818c39d97ad7a1cdf6e075b9acae6dfff71/boot/opensbi/`  package? I saw it has been built.

Regards,
yf

**Comment by LearnigF** [comment]
MPP is known as Media Process Platform, which includes the k230's multimedia kernel driver as well as the userland API library and sample code.
CDK:Communication Development Kit,indicates the development kit for multi-core communication; under CDK, there are IPCM, datafifo, MAPI, etc., the contents are all related to heterogeneous core communication.

Regarding opensbi's question, need another colleague to reply to you。

**Comment by yf13** [comment]
@LearnigF can I take that CDK is a proprietary alternative of OpenAMP? if so, is there any possibility to have OpenAMP on K230?

**Comment by yf13** [comment]
@LearnigF did you mean that OpenAMP can run on K230, but it doesn't meet requirements of demo applications? If so, can you teach a few specific points?

**Comment by LearnigF** [comment]
Hello I think it's theoretically possible to port openAMP, but we have no plans to do that at the moment。

**Comment by LearnigF** [comment]
If you have commercial product development and need to transplant openamp to k230, you can contact us at the email address below the sdk readme
