### ISSUE TITLE
[other]:  如何关闭大核和 rtthread

### ISSUE THREAD

**Issue by Qinka** [kendryte/k230_docs#12]
### Other

我们当前不需要使用大核与 rt-thread ，所以，如何把这两个东西关闭或者禁用，以将低功耗？

**Comment by zhangxiaojingCAN** [comment]
大核有单独的电源域控制，可以在uboot中讲大核电源域关闭来达到降低功耗目标。目前SDK尚未支持这个功能，会在之后的版本中增加。

**Comment by chenhb3** [comment]
7天以上未反馈结果，问题先关闭；希望已帮助您解决问题，谢谢！
