### ISSUE TITLE
[other]: 请问如何设置自启应用？

### ISSUE THREAD

**Issue by roingbu** [kendryte/k230_docs#14]
### Other

请问如何设置自启应用？
我需要将默认的自启应用换成我自己的.elf应用，请问该如何做到？

**Comment by MrThanlon** [comment]
大核rt-smart 修改 `src/big/rt-smart/init.sh` 然后重新编译镜像

**Comment by roingbu** [comment]
但是自己的二进制文件和kmodel还是编译不进去，编译会出错。如何将自己的二进制文件及kmodel编译进去呢

**Comment by MrThanlon** [comment]
要放文件到romfs可以放到 `src/big/rt-smart/userapps/root` 目录下，编译报错报的什么错可以贴上来

**Comment by superbinary-code** [comment]
如要更改默认应用为face_landmark，如下，修改src/big/rt-smart/init.sh 
# /bin/fastboot_app.elf /bin/test.kmodel
/bin/face_landmark.elf /bin/face_detection_320.kmodel 0.6 0.2 /bin/face_landmark.kmodel None 0

并且把face_landmark.elf和这两个kmodel文件copy到k230_sdk/src/big/rt-smart/userapps/root/bin下面，再重新编译镜像烧录即可

**Comment by chenhb3** [comment]
7天以上未反馈结果，问题先关闭；希望已帮助您解决问题；后续有其它问题再重新创建，谢谢！

**Comment by gjhave** [comment]
请参考/src/big/mpp/userapps/sample/fastboot_app中的代码和相关makefile配置，具体步骤如下：
1、在/src/big/mpp/userapps/sample文件夹下建立你的项目文件夹，例如my_detect，在文件夹中添加源代码和相应的CMakeList.txt,
2、把你训练好的test.kmodel文件复制到/src/big/kmodel/my_detect/目录下
2、在/src/big/mpp/userapps/sample文件下创建my_detect_elf文件夹，编译后的elf文件和test.kmodel会自动copy到该目录。目录文件及相应的CMakeList.txt文件修改如图
![项目文件夹](https://github.com/kendryte/k230_docs/assets/23455362/f5570eee-9cea-4bd0-a2f2-b82da8f96438)

2、修改/src/big/mpp/userapps/sample/Makefile文件如图
![sample makefile 1](https://github.com/kendryte/k230_docs/assets/23455362/777d31c6-b9b7-4d2b-aa75-2d45ae934348)
![sample makefile 2](https://github.com/kendryte/k230_docs/assets/23455362/695d0845-c460-4f73-8333-feedf4720b21)

3、修改k230_sdk/Makefile中的mpp-apps部分文件如图
![k230_sdk makefile](https://github.com/kendryte/k230_docs/assets/23455362/66cce063-de57-4d17-84fd-dbe12ccb07f3)

4、修改/src/big/rt-smart/init.sh文件如图
![init_sh](https://github.com/kendryte/k230_docs/assets/23455362/3ab738a2-54ac-4097-aaa9-16ac89b8a318)

5、在k230_sdk文件夹下make rt-smart && make build-image，生成的镜像烧录即可启动运行hello_world.elf
