### ISSUE TITLE
[other]: 双核操作系统的具体版本

### ISSUE THREAD

**Issue by wusnga8dn** [kendryte/k230_docs#2]
### Other

我看到k230双核的操作系统是rt-smart+linux，请问在小核的linux系统仅仅是一个linux内核还是一个完整的类似于Ubuntu的桌面操作系统？

**Comment by gyangcan** [comment]
你好！
K230的小核linux系统，是嵌入式linux系统，基于linux 5.10版本内核和buildroot框架构建，不是linux发行版的桌面操作系统。

**Comment by wusnga8dn** [comment]
> 你好！ K230的小核linux系统，是嵌入式linux系统，基于linux 5.10版本内核和buildroot框架构建，不是linux发行版的桌面操作系统。

你好我想问一下大核是否支持vmRT-thread

**Comment by gyangcan** [comment]
大核没有支持vmRT-thread
