### ISSUE TITLE
[Errata]: strange FPS value for camera sensors

### ISSUE THREAD

**Issue by yf13** [kendryte/k230_docs#20]
### Errata

The [sensor adaption guide](https://gitee.com/kendryte/k230_docs/blob/main/zh/01_software/board/mpp/K230_Camera_Sensor%E9%80%82%E9%85%8D%E6%8C%87%E5%8D%97.md#%E6%A6%82%E8%BF%B0) uses 30000 as FPS values. 

Could you explain why this value is used? I can't see  supported cameras can reach such high frame rate.

**Comment by wangchenggen** [comment]
This values is 1000 times of the actual frame rate.

**Comment by yf13** [comment]
Okay, please mention it in documents later.
