### ISSUE TITLE
[other]: can't find "/path/to/k230_sdk/src/big/utils/examples/hhb"

### ISSUE THREAD

**Issue by stedylan** [kendryte/k230_docs#22]
### Other

in my workspace, can't see utils folder
`➜  big git:(main) ✗ ls
kmodel  mpp  nncase  rt-smart  unittest
➜  big git:(main) ✗ pwd
/home/sail/repo/k230_sdk/src/big`

**Comment by wuwentao** [comment]
your may not follow our document and steps.
please refer to our README.md at https://github.com/kendryte/k230_sdk


```shell
docker pull ghcr.io/kendryte/k230_sdk

git clone https://github.com/kendryte/k230_sdk
cd k230_sdk
make prepare_sourcecode
docker run -u root -it -v $(pwd):$(pwd) -v $(pwd)/toolchain:/opt/toolchain -w $(pwd) ghcr.io/kendryte/k230_sdk /bin/bash

make CONF=k230_evb_defconfig
```
