### ISSUE TITLE
[other]: 关于板子sharefs不存在的问题？

### ISSUE THREAD

**Issue by HadXu** [kendryte/k230_docs#27]
### Other

1. 如[K230_实战基础篇_hello_world.md](https://github.com/kendryte/k230_docs/blob/main/zh/02_applications/tutorials/K230_%E5%AE%9E%E6%88%98%E5%9F%BA%E7%A1%80%E7%AF%87_hello_world.md)所示，将代码编译后放到sdcard中 app下在大核中能够看到该可执行程序，可以直接执行。
2. 在大核中无法看到/sharefs文件夹 

![image](https://github.com/kendryte/k230_docs/assets/13307469/8c3d2fdd-c68a-4511-8f17-90a1dd4d0cf3)

因此我只能将hello_world产生的文件放到sdcard的app中，在大核中去运行，小核无法看到。

固件为[CanMV-K230_micropython_v0.3_sdk_v1.1_nncase_v2.4.0.img.gz](https://kendryte-download.canaan-creative.com/developer/k230/CanMV-K230_micropython_v0.3_sdk_v1.1_nncase_v2.4.0.img.gz)

**Comment by HadXu** [comment]
edit.

**Comment by wuwentao** [comment]
首先需要明确的是：虽然micropython镜像基于k230 sdk，但是细节功能方面还是稍有差异，
……
**因此micropythond的文档也是独立在k230_sdk文档之外的，因此请参考[k230_canmv_docs](https://github.com/kendryte/k230_canmv_docs)文档的使用说明。**

下一个release版本可以使用类似k230 sdk固件的这个/sharefs的方案，我们已经加上了，但是仍在测试中，尚未release。
最后仍然需要提醒，不代表k230 sdk的所有功能都与micropython固件完全一样或直接照搬就能使用，还是有差异性的，否则咱们也没必要搞这么多不同的固件。

**Comment by HadXu** [comment]
感谢回复。
关于板子的使用目前仍有迷惑的地方。

1. 第一个就是文档中说明
![image](https://github.com/kendryte/k230_docs/assets/13307469/ec3176ad-d61f-49a2-8d89-1900a3562f58)
但是我实际测试并没有发现USB串行设备，只有大核和小核两个串口。

2. 在从其他机器拷贝文件的时候
![image](https://github.com/kendryte/k230_docs/assets/13307469/27472ef2-5d2d-4858-bb33-342947247319)

3. 机器开启之后通过HDMI屏幕并没有显示。

**Comment by HadXu** [comment]
我理想的开发状态是能够ssh进去，然后在k230上进行编译，或者交叉编译通过网络将可执行文件放到板子上运行。能够将RVV跑起来，以及一些其他的调试即可。

**Comment by wangjianxin-canaan** [comment]
> 在下载一些其他的固件，发现并不存在
> 
> 
![screenshot-20240124-140734](https://github.com/kendryte/k230_docs/assets/102512117/f05db027-f341-4f41-930a-c40afb311391)

需要点击左边的 K230  Images

**Comment by wangjianxin-canaan** [comment]
> 发状态是能够ssh进去，然后在k230上进行编译，或者交叉编译通过网络将可执行文件放到板子上运行。能够将RVV跑起来，以及一些其他的调试即可。

canmv_ubuntu_sdcard_1.3.img.gz 或canmv_debian_sdcard_sdk_1.3.img.gz 可以，直接下载sdk源码编译k230_canmv_only_linux_defconfig 也可以

**Comment by wangjianxin-canaan** [comment]
> > 在下载一些其他的固件，发现并不存在
> 
> ![screenshot-20240124-140734](https://private-user-images.githubusercontent.com/102512117/299201685-f05db027-f341-4f41-930a-c40afb311391.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzcwNzEsIm5iZiI6MTcwNjA3Njc3MSwicGF0aCI6Ii8xMDI1MTIxMTcvMjk5MjAxNjg1LWYwNWRiMDI3LWYzNDEtNGY0MS05MzBhLWM0MGFmYjMxMTM5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQwNjEyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTAxOWNkZTM1ZTk2OTg4ZTVhZDlmZjUyY2EwYjNkNmI2NzVhYThiNTBhM2NkOTE2NmNlYWMxNDA0OTllMWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TI8_53cNbGH1gSTyTSfXqGFuUU5mDvCki_0FzTzCLNc)
> 
> 需要点击左边的 K230 Images

---目前确实有问题，我也下载不了。

**Comment by MrThanlon** [comment]
> 在下载一些其他的固件，发现并不存在
> 
> ![image](https://private-user-images.githubusercontent.com/13307469/299198100-655eb68f-17d3-407c-a0fc-3507fed3b36c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzcwMjksIm5iZiI6MTcwNjA3NjcyOSwicGF0aCI6Ii8xMzMwNzQ2OS8yOTkxOTgxMDAtNjU1ZWI2OGYtMTdkMy00MDdjLWEwZmMtMzUwN2ZlZDNiMzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZTc5NzNkNTljZDBhYTI3NmNmNzUyZDNhMjQ0YjdkMmFhMWQxMTUzNzE0NzA5NjdmODQ3YTNmY2NhM2Y5NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yq4Jl8dGqFxysngPRHpXuFxY7tG-7uAjX3rGakC-nek)

已修复

**Comment by wangjianxin-canaan** [comment]
> 感谢回复。 关于板子的使用目前仍有迷惑的地方。
> 
> 1. 第一个就是文档中说明
>    ![image](https://private-user-images.githubusercontent.com/13307469/299197039-ec3176ad-d61f-49a2-8d89-1900a3562f58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzcxODMsIm5iZiI6MTcwNjA3Njg4MywicGF0aCI6Ii8xMzMwNzQ2OS8yOTkxOTcwMzktZWMzMTc2YWQtZDYxZi00OWEyLThkODktMTkwMGEzNTYyZjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2MTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMWFiMTZiMmE0NzE5MTk0NTBlNzRmZWU3ZWNmNWQ1MGRmOWZlNTNmMzVhYTI5NjRjNGVmMDk2MWY1NTI1ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IVqDJoQv7DDx_5FB9g1PbB7LE_ueYpwJlD0iTEB3diI)
>    但是我实际测试并没有发现USB串行设备，只有大核和小核两个串口。
> 2. 在从其他机器拷贝文件的时候
>    ![image](https://private-user-images.githubusercontent.com/13307469/299197481-27472ef2-5d2d-4858-bb33-342947247319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzcxODMsIm5iZiI6MTcwNjA3Njg4MywicGF0aCI6Ii8xMzMwNzQ2OS8yOTkxOTc0ODEtMjc0NzJlZjItNWQyZC00ODU4LWJiMzMtMzQyOTQ3MjQ3MzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2MTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNzJkZTFiMDI0YzllODJkYTdlZDhlNWQ1NTcwZGM3YmE2MDY5ZDc3YjMxYzk4MzVjYmM5N2Q5NThlYTM0ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b9he_Q0-aVXIhfPmpxkuurDWgKMts18hTaMDO_bh_gU)
> 3. 机器开启之后通过HDMI屏幕并没有显示。

问题1：2个usb线均连接，按下reset按键，等1分钟系统起来后，再看
问题2：micropython固件，主要功能是运行在大核这边的micropython。小核这边运行很小的linux系统(裁掉了加密库)
问题3：请使用sdk固件，不要下载带micropython的固件

**Comment by zhaohu5188** [comment]
> 感谢回复。 关于板子的使用目前仍有迷惑的地方。
> 
> 1. 第一个就是文档中说明
>    ![image](https://private-user-images.githubusercontent.com/13307469/299197039-ec3176ad-d61f-49a2-8d89-1900a3562f58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzY3NDcsIm5iZiI6MTcwNjA3NjQ0NywicGF0aCI6Ii8xMzMwNzQ2OS8yOTkxOTcwMzktZWMzMTc2YWQtZDYxZi00OWEyLThkODktMTkwMGEzNTYyZjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2MDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNzkxMjM2NzBkNDRmZjVhNjA4MTQwYjVmZDY4NjZjZjVmMGJlNmUxYWZjNDNhZDc4ZDI4MWMyODllZmM4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b8b6M3kDuj5FwT8HZkmhkwiNhUANUlGxrtNxA-l4g3c)
>    但是我实际测试并没有发现USB串行设备，只有大核和小核两个串口。
> 2. 在从其他机器拷贝文件的时候
>    ![image](https://private-user-images.githubusercontent.com/13307469/299197481-27472ef2-5d2d-4858-bb33-342947247319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzY3NDcsIm5iZiI6MTcwNjA3NjQ0NywicGF0aCI6Ii8xMzMwNzQ2OS8yOTkxOTc0ODEtMjc0NzJlZjItNWQyZC00ODU4LWJiMzMtMzQyOTQ3MjQ3MzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2MDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNmQxNjdhNjhkNTE3MTU4OWQyYmU5N2E1MTNiZDgzODUyODYxYTMwNjIxMzUzZDc4OGE2NmVjZGQyYTQ3ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qF_a7q7Rw0du2k2tZjG7Iy-95FdRMeSkCcH94nk61xM)
> 3. 机器开启之后通过HDMI屏幕并没有显示。

1、需要两根USB数据线，两USB口都要连接电脑。

3、使用确定使用的是k230_canmv_sdcard ... 开头的镜像， micropython的镜像默认HDMI没有显示。

**Comment by HadXu** [comment]
> > 在下载一些其他的固件，发现并不存在
> > ![image](https://private-user-images.githubusercontent.com/13307469/299198100-655eb68f-17d3-407c-a0fc-3507fed3b36c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzcwMjksIm5iZiI6MTcwNjA3NjcyOSwicGF0aCI6Ii8xMzMwNzQ2OS8yOTkxOTgxMDAtNjU1ZWI2OGYtMTdkMy00MDdjLWEwZmMtMzUwN2ZlZDNiMzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZTc5NzNkNTljZDBhYTI3NmNmNzUyZDNhMjQ0YjdkMmFhMWQxMTUzNzE0NzA5NjdmODQ3YTNmY2NhM2Y5NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yq4Jl8dGqFxysngPRHpXuFxY7tG-7uAjX3rGakC-nek)
> 
> 已修复

https://kendryte-download.canaan-creative.com/developer/canmv_ubuntu_sdcard_1.3.img.gz

仍然无法下载-----

**Comment by MrThanlon** [comment]
> > > 在下载一些其他的固件，发现并不存在
> > > ![image](https://private-user-images.githubusercontent.com/13307469/299198100-655eb68f-17d3-407c-a0fc-3507fed3b36c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzcwMjksIm5iZiI6MTcwNjA3NjcyOSwicGF0aCI6Ii8xMzMwNzQ2OS8yOTkxOTgxMDAtNjU1ZWI2OGYtMTdkMy00MDdjLWEwZmMtMzUwN2ZlZDNiMzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZTc5NzNkNTljZDBhYTI3NmNmNzUyZDNhMjQ0YjdkMmFhMWQxMTUzNzE0NzA5NjdmODQ3YTNmY2NhM2Y5NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yq4Jl8dGqFxysngPRHpXuFxY7tG-7uAjX3rGakC-nek)
> > 
> > 
> > 已修复
> 
> https://kendryte-download.canaan-creative.com/developer/canmv_ubuntu_sdcard_1.3.img.gz
> 
> 仍然无法下载-----

刷新下浏览器，链接是 https://kendryte-download.canaan-creative.com/developer/k230/canmv_ubuntu_sdcard_1.3.img.gz

**Comment by HadXu** [comment]
> > > > 在下载一些其他的固件，发现并不存在
> > > > ![image](https://private-user-images.githubusercontent.com/13307469/299198100-655eb68f-17d3-407c-a0fc-3507fed3b36c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzcwMjksIm5iZiI6MTcwNjA3NjcyOSwicGF0aCI6Ii8xMzMwNzQ2OS8yOTkxOTgxMDAtNjU1ZWI2OGYtMTdkMy00MDdjLWEwZmMtMzUwN2ZlZDNiMzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZTc5NzNkNTljZDBhYTI3NmNmNzUyZDNhMjQ0YjdkMmFhMWQxMTUzNzE0NzA5NjdmODQ3YTNmY2NhM2Y5NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yq4Jl8dGqFxysngPRHpXuFxY7tG-7uAjX3rGakC-nek)
> > > 
> > > 
> > > 已修复
> > 
> > 
> > https://kendryte-download.canaan-creative.com/developer/canmv_ubuntu_sdcard_1.3.img.gz
> > 仍然无法下载-----
> 
> 刷新下浏览器，链接是 https://kendryte-download.canaan-creative.com/developer/k230/canmv_ubuntu_sdcard_1.3.img.gz

另一个问题，登陆账号与密码默认是什么？在文档中并没有找打相关信息。

**Comment by HadXu** [comment]
> > > > > 在下载一些其他的固件，发现并不存在
> > > > > ![image](https://private-user-images.githubusercontent.com/13307469/299198100-655eb68f-17d3-407c-a0fc-3507fed3b36c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzcwMjksIm5iZiI6MTcwNjA3NjcyOSwicGF0aCI6Ii8xMzMwNzQ2OS8yOTkxOTgxMDAtNjU1ZWI2OGYtMTdkMy00MDdjLWEwZmMtMzUwN2ZlZDNiMzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZTc5NzNkNTljZDBhYTI3NmNmNzUyZDNhMjQ0YjdkMmFhMWQxMTUzNzE0NzA5NjdmODQ3YTNmY2NhM2Y5NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yq4Jl8dGqFxysngPRHpXuFxY7tG-7uAjX3rGakC-nek)
> > > > 
> > > > 
> > > > 已修复
> > > 
> > > 
> > > https://kendryte-download.canaan-creative.com/developer/canmv_ubuntu_sdcard_1.3.img.gz
> > > 仍然无法下载-----
> > 
> > 
> > 刷新下浏览器，链接是 https://kendryte-download.canaan-creative.com/developer/k230/canmv_ubuntu_sdcard_1.3.img.gz
> 
> 另一个问题，登陆账号与密码默认是什么？在文档中并没有找打相关信息。

已解决 ”echo "root:root" | chpasswd“

**Comment by HadXu** [comment]
貌似网口不能使用以及大核无法使用。

**Comment by wangjianxin-canaan** [comment]
> 貌似网口不能使用以及大核无法使用。
ubuntu镜像运行在大核。
当前版本网口初始化驱动有点问题，如果起来后网口找不到，请重启下设备。

**Comment by HadXu** [comment]
重启了很多次设备 网口无法正常运行。 镜像为[canmv_ubuntu_sdcard_1.3.img.gz](https://kendryte-download.canaan-creative.com/developer/k230/canmv_ubuntu_sdcard_1.3.img.gz)

**Comment by wuwentao** [comment]
close当前issue，请使用最新的镜像或源码验证，当前issue已经完全脱离标题和内容了，如果仍然有具体的细节问题，可以单独提交不同的issue，分别跟踪，分别处理，而不是一个issue里面赛进一堆各种各样的问题来跟踪，导致无法进行后续的处理。
