### ISSUE TITLE
[other]: Access to the Performance Timers (Counters)

### ISSUE THREAD

**Issue by bgin** [kendryte/k230_docs#29]
### Other

Hello,
Does there exist a possibility to directly access the k230 performance timers or counters from the user space?
Just as in the case of x86_64 architecture where exists a dedicated instruction i.e. "RDPMC".

Thank your for help
Best regards
Bernard

**Comment by bgin** [comment]
@wuwentao , @zhangxiaojingCAN , @sunnycase 
Can anyone answer my question!!

**Comment by wycwyhwyq** [comment]
```c
uint64_t get_cpu_times(void)
{
    uint64_t value;
    __asm__ __volatile__("rdtime %0" : "=r"(value));
    return value;
}

uint64_t get_cpu_cycles(void)
{
    uint64_t value;
    __asm__ __volatile__("rdcycle %0" : "=r"(value));
    return value;
}
```

The cpu timer frequency is 24M Hz.
The big core cpu default frequency is 1.6G Hz.
The little core cpu default frequency is 800M Hz.

**Comment by bgin** [comment]
> ```c
> uint64_t get_cpu_times(void)
> {
>     uint64_t value;
>     __asm__ __volatile__("rdtime %0" : "=r"(value));
>     return value;
> }
> 
> uint64_t get_cpu_cycles(void)
> {
>     uint64_t value;
>     __asm__ __volatile__("rdcycle %0" : "=r"(value));
>     return value;
> }
> ```
> 
> The cpu timer frequency is 24M Hz. The big core cpu default frequency is 1.6G Hz. The little core cpu default frequency is 800M Hz.

@wycwyhwyq 
Thank you very much.

I have additional question and let me explain that more profoundly.
Why looking at perf-list output I have seen much greater number of hardware-events, that those presented by you.
Please have a look:
![image](https://github.com/kendryte/k230_docs/assets/11363675/57ef150c-89d1-4414-8745-8a44e195c85e)
and this screenshot:
![image](https://github.com/kendryte/k230_docs/assets/11363675/08caf72c-d79f-4cdf-8776-b533d5bd8c68)

I would like to know if there is a possibility to read these hardware events from the user space, exactly just as your example shows the read-out of timer value and the cycle count.

I really appreciate your help!!

Bernard

**Comment by wycwyhwyq** [comment]
For a detailed introduction and use of PMU, please refer to Chapter 14 of this [XuanTie-C908-UserManual.pdf](https://occ-intl-prod.oss-ap-southeast-1.aliyuncs.com/resource//1699268369347/XuanTie-C908-UserManual.pdf).

**Comment by wuwentao** [comment]
as there is no any new response in current issue for a long time, so we will close it.
if issue still exist or need more info, we still can reopen current issue.
Thanks!
