### ISSUE TITLE
[Errata]: 启动报错代码19

### ISSUE THREAD

**Issue by 1buxiangqimingzi1** [kendryte/k230_docs#31]
### Errata

![415e63f01ddc90e00714b79f9c48889](https://github.com/kendryte/k230_docs/assets/142566494/e29e5376-c20d-4f19-b099-10078127435d)

**Comment by 1buxiangqimingzi1** [comment]
我想请问一下这个代码19对应的是什么问题

**Comment by wuwentao** [comment]
错误信息应该算是比较清晰了，boot  failed，需要检查对应的启动介质是否是使用的可启动的镜像，也就是SD卡里面的内容，不是复制文件进去，是要烧录重写sd卡镜像，基本就解决问题了。

如果是使用的之前早期的evb板卡，还需通过拨码开关，来选择对应的启动介质，需确认拨码开关所处位置，单一启动介质基本上只有sd卡了。

就纠结每个错误码的具体含义，如果作为开发者，就想了解的更清楚一些，就希望了解和查询错误码以及具体定义，建议还是直接参考源码吧，目前应该没有把类似这种底层细节的错误码都写到文档里面的。
如果想自己处理启动流程，但自行仍然找不到这一块源码在哪里，可以继续提问，再协助说明具体在哪一块吧。
文档里面应该启动优化的，建议先参考文档：
https://github.com/kendryte/k230_docs/blob/main/zh/02_applications/tutorials/K230_%E5%90%AF%E5%8A%A8%E4%BC%98%E5%8C%96%E6%8C%87%E5%8D%97.md

开发细节方面不明确的地方，再针对具体代码和问题进行沟通吧

**Comment by wuwentao** [comment]
超过一个月未收到后续回复，先close当前issue了
如果针对当前问题仍然不确定的，仍然针对当前issue有疑问，可以继续沟通，或者reopen当前issue。
