### ISSUE TITLE
[other]: source code of micropython that K230 use

### ISSUE THREAD

**Issue by FrogKuma** [kendryte/k230_docs#35]
### Other

Where Can I find the source code or API of micropython that used in K230 or? There's some functions that are not contained in regular micropython and I cannot find any docs about them.

**Comment by wuwentao** [comment]
@FrogKuma 

https://developer.canaan-creative.com/document
https://developer.canaan-creative.com/k230_canmv/main/index.html

**Comment by wuwentao** [comment]
@FrogKuma if you really read the document, you should not submit this issue to request the source code
for example:
https://developer.canaan-creative.com/k230_canmv/main/zh/userguide/how_to_build.html
