### ISSUE TITLE
[Errata]: 如何用设备树和sysfs来控制PMU 

### ISSUE THREAD

**Issue by roingbu** [kendryte/k230_docs#5]
### Errata

问题1：我不知如何使用设备树控制PMU，文档也无相关过程（教程）
问题2：另外还有个问题，我烧进emmc的系统内，并无/sys/devices/platform/soc/91000000.pmu
如下图
![image](https://github.com/kendryte/k230_docs/assets/31338524/e03bcf37-8bb6-4afb-823e-848ce8a86e3a)

问题3：k230有无休眠模式

**Comment by wycwyhwyq** [comment]
问题1：请参考 [K230 PMU使用文档](https://github.com/kendryte/k230_docs/blob/main/zh/01_software/board/osdrv/K230_PMU_%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.md)
问题2：PMU模块在设备树中默认是未使能的，如果需要使用请在设备树中使能后，重新编译
问题3：暂不支持休眠模式

备注：使用PMU模块需要更改电路板连接和通过INT唤醒系统，相关信息参考使用文档

**Comment by roingbu** [comment]
额……设备树在哪，我该怎么控制它？

**Comment by wycwyhwyq** [comment]
[PMU设备树地址](https://github.com/kendryte/k230_sdk/blob/41f7d1ca6dcfd8c98202110479c73e542d1af9c3/src/little/linux/arch/riscv/boot/dts/kendryte/k230_evb.dtsi#L172C5-L172C5)

**Comment by Qinka** [comment]
> 问题3：暂不支持休眠模式

话说，什么时候能支持休眠模式呢？或者说，如何修改代码，来支持休眠模式

**Comment by chenhb3** [comment]
暂时没有明确的计划

**Comment by chenhb3** [comment]
超过7天未再反馈，问题将关闭，后续若有问题可重新创建，感谢关注！
