### ISSUE TITLE
[Errata]: A path error lying in the command line in the "hello_world.md"

### ISSUE THREAD

**Issue by BHbean** [kendryte/k230_docs#8]
### Errata

In the `k230_docs/zh/02_applications/tutorials/K230_实战基础篇_hello_world.md` file, there is a path error in the line 93:
![image](https://github.com/kendryte/k230_docs/assets/66934674/3782f9bf-c9ad-43a8-a66f-9d09c74bee47)
I am going to create a PR to fix it, hope it would be helpful!

**Comment by chenhb3** [comment]
Thank you,it will be merge into next version.
